apiVersion: v1
kind: Secret
metadata:
  name: {{ include "truenas-password-changer.fullname" . }}-secret
  labels:
    {{- include "truenas-password-changer.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ required "truenas.apiKey is required" .Values.truenas.apiKey | b64enc | quote }}
  flask-secret: {{ .Values.flask.secretKey | default (randAlphaNum 32) | b64enc | quote }}
